# Cấu hình cho môi trường dev (local)
spring:
  datasource:
    url: jdbc:mysql://metro.proxy.rlwy.net:15098/railway
    username: root
    password: PxyBWzYShxdKhyPOPUdkPdvfHHGsosoA
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    redis:
      host: nozomi.proxy.rlwy.net
      port: 58945
      username: default
      password: sWwiojuVHEKkDIKzPlwoxMCPDgILUdCZ

feign:
  client:
    config:
      default:
        loggerLevel: full

email-client:
  url: https://api.brevo.com

admin:
  email: admin@yourdomain.com
  password: your_admin_password

jwt:
  secretKey: your_jwt_secret_key

cloudinary-url: https://api.cloudinary.com/v1_1/your_cloud_name

brevo:
  api:
    key: your_brevo_api_key
  sender:
    name: Your Name
    email: sender@yourdomain.com

google:
  client:
    id: your_google_client_id
    secret: your_google_client_secret
  redirect:
    uri: http://localhost:3000/oauth2/callback

springdoc:
  swagger-ui:
    enabled: true
    path: /docs
    display-request-duration: true

logging:
  level:
    org:
      springframework: DEBUG
      apache:
        tomcat: DEBUG
        catalina: DEBUG