# config cho môi trường chung
spring:
  profiles:
    active:
      dev
  messages:
    basename: i18n/messages
    encoding: UTF-8

server:
  port: 8080
  servlet:
    context-path: /api

app:
  name: TRO_HUB

otp:
  expiration: 5    # phút
  resend: 120      # giây

jwt:
  valid-duration: 7200
  refreshable-duration: 1209600

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

springdoc:
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org:
      springframework: INFO