# Cấu hình cho môi trường dev (local)
spring:
  datasource:
    url: your_database_url_here
    username: your_database_username_here
    password: your_database_password_here
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    redis:
      host: your_redis_host_here
      port: 123456 # replace with your actual Redis port
      username: your_redis_username_here
      password: your_redis_password_here

feign:
  client:
    config:
      default:
        loggerLevel: full

email-client:
  url: your_email_client_url_here

admin:
  email: admin@yourdomain.com
  password: your_admin_password

jwt:
  secretKey: your_jwt_secret_key

cloudinary-url: your_cloudinary_url_here

brevo:
  api:
    key: your_brevo_api_key
  sender:
    name: Your Name
    email: sender@yourdomain.com

google:
  client:
    id: your_google_client_id
    secret: your_google_client_secret
  redirect:
    uri: your_redirect_uri_here

springdoc:
  swagger-ui:
    enabled: true
    path: /docs
    display-request-duration: true

logging:
  level:
    org:
      springframework: DEBUG
      apache:
        tomcat: DEBUG
        catalina: DEBUG