# config cho môi trường thực tế
server:
  port: ${PORT}
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://metro.proxy.rlwy.net:15098/railway
    username: root
    password: PxyBWzYShxdKhyPOPUdkPdvfHHGsosoA
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    redis:
      host: nozomi.proxy.rlwy.net
      port: 58945
      username: default
      password: sWwiojuVHEKkDIKzPlwoxMCPDgILUdCZ

feign:
  client:
    config:
      default:
        loggerLevel: none  # ẩn log http ở môi trường thật

email-client:
  url: ${EMAIL_URL}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

jwt:
  secretKey: ${JWT_SIGNER_KEY}

cloudinary-url: ${CLOUDINARY_URL}

brevo:
  api:
    key: ${API_KEY}
  sender:
    name: ${SENDER_NAME}
    email: ${SENDER_EMAIL}

google:
  client:
    id: ${CLIENT_ID}
    secret: ${CLIENT_SECRET}
  redirect:
    uri: ${REDIRECT_URI}

springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    org:
      springframework: DEBUG
      apache:
        tomcat: DEBUG
        catalina: DEBUG