# application-dev.example.yaml

# Cấu hình cho môi trường dev (local)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name
    username: your_db_username
    password: your_db_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    redis:
      host: localhost
      port: 6379
      username: your_redis_username
      password: your_redis_password

feign:
  client:
    config:
      default:
        loggerLevel: full

email-client:
  url: https://api.brevo.com

admin:
  email: admin@yourdomain.com
  password: your_admin_password

jwt:
  secretKey: your_jwt_secret_key

cloudinary-url: https://api.cloudinary.com/v1_1/your_cloud_name

brevo:
  api:
    key: your_brevo_api_key
  sender:
    name: Your Name
    email: sender@yourdomain.com

google:
  client:
    id: your_google_client_id
    secret: your_google_client_secret
  redirect:
    uri: http://localhost:3000/oauth2/callback

logging:
  level:
    org:
      springframework: DEBUG
      apache:
        tomcat: DEBUG
        catalina: DEBUG