jwt:
  secretKey: ${JWT_SIGNER_KEY}
  valid-duration: 7200
  refreshable-duration: 1209600

cloudinary-url: ${CLOUDINARY_URL}

brevo:
  api:
    key: ${API_KEY}
  sender:
    name: ${SENDER_NAME}
    email: ${SENDER_EMAIL}

otp:
  expiration: 5 # phút
  resend: 120 # giây

google:
  client:
    id: ${CLIENT_ID}
    secret: ${CLIENT_SECRET}
  redirect:
    uri: ${REDIRECT_URI}