package com.example.datn_qlnt_manager.exception;

import com.example.datn_qlnt_manager.configuration.Translator;
import org.springframework.http.HttpStatus;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.experimental.FieldDefaults;

@Getter
@FieldDefaults(level = AccessLevel.PRIVATE)
public enum  ErrorCode {
    // Code: 500
    INTERNAL_SERVER_ERROR(500, Translator.toLocale("internal.server.error"), HttpStatus.INTERNAL_SERVER_ERROR),
    UPLOAD_FAILED(500, Translator.toLocale("upload.failed"), HttpStatus.INTERNAL_SERVER_ERROR),
    JSON_PROCESSING_ERROR(500, Translator.toLocale("json.processing.error"), HttpStatus.INTERNAL_SERVER_ERROR),

    // Code: 401
    UNAUTHORIZED(401, Translator.toLocale("unauthorized"), HttpStatus.UNAUTHORIZED),
    INVALID_TOKEN_FORMAT(401, Translator.toLocale("invalid.token.format"), HttpStatus.UNAUTHORIZED),
    INVALID_SIGNATURE(401, Translator.toLocale("invalid.signature"), HttpStatus.UNAUTHORIZED),
    EXPIRED_TOKEN(401, Translator.toLocale("expired.token"), HttpStatus.UNAUTHORIZED),
    TOKEN_BLACKLISTED(401, Translator.toLocale("token.blacklisted"), HttpStatus.UNAUTHORIZED),

    // Code: 403
    FORBIDDEN(403, Translator.toLocale("forbidden"), HttpStatus.FORBIDDEN),
    CANT_REMOVE_USER(403, Translator.toLocale("cant.remove.user"), HttpStatus.FORBIDDEN),
    ACCOUNT_HAS_BEEN_LOCKED(403, Translator.toLocale("account.has.been.locked"), HttpStatus.FORBIDDEN),
    FORBIDDEN_CATEGORY_TYPE(
            400, Translator.toLocale("forbidden.category.type"), HttpStatus.FORBIDDEN),

    // Code: 400
    BAD_REQUEST(400, Translator.toLocale("bad.request"), HttpStatus.BAD_REQUEST),
    CANNOT_SEND_EMAIL(400, Translator.toLocale("cannot.send.email"), HttpStatus.BAD_REQUEST),
    EMAIL_SENDING_FAILED(400, Translator.toLocale("email.sending.failed"), HttpStatus.BAD_REQUEST),
    INVALID_KEY(400, Translator.toLocale("invalid.key"), HttpStatus.BAD_REQUEST),
    INVALID_TOKEN(400, Translator.toLocale("invalid.token"), HttpStatus.BAD_REQUEST),
    USER_NOT_DELETED(400, Translator.toLocale("user.not.deleted"), HttpStatus.BAD_REQUEST),
    USER_NOT_LOCKED(400, Translator.toLocale("user.not.locked"), HttpStatus.BAD_REQUEST),
    INVALID_EMAIL_BLANK(400, Translator.toLocale("invalid.email.blank"), HttpStatus.BAD_REQUEST),
    INVALID_EMAIL_FORMAT(400, Translator.toLocale("invalid.email.format"), HttpStatus.BAD_REQUEST),
    INVALID_EMAIL_OR_PASSWORD(400, Translator.toLocale("invalid.email.or.password"), HttpStatus.BAD_REQUEST),
    INVALID_FULL_NAME(400, Translator.toLocale("invalid.full.name"), HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD(400, Translator.toLocale("invalid.password"), HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD_BLANK(400, Translator.toLocale("invalid.password.blank"), HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD_LENGTH(400, Translator.toLocale("invalid.password.length"), HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD_UPPERCASE(400, Translator.toLocale("invalid.password.uppercase"), HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD_LOWERCASE(400, Translator.toLocale("invalid.password.lowercase"), HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD_NUMBER(400, Translator.toLocale("invalid.password.number"), HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD_SPECIAL_CHARACTERS(
            400, Translator.toLocale("invalid.password.special.characters"), HttpStatus.BAD_REQUEST),
    INVALID_GENDER_BLANK(400, Translator.toLocale("invalid.gender.blank"), HttpStatus.BAD_REQUEST),
    INVALID_DOB(400, Translator.toLocale("invalid.dob"), HttpStatus.BAD_REQUEST),
    INVALID_PHONE(400, Translator.toLocale("invalid.phone"), HttpStatus.BAD_REQUEST),
    INVALID_PHONE_BLANK(400, Translator.toLocale("invalid.phone.blank"), HttpStatus.BAD_REQUEST),
    PASSWORDS_CONFIRM_NOT_MATCH(400, Translator.toLocale("passwords.confirm.not.match"), HttpStatus.BAD_REQUEST),
    NEW_PASSWORD_SAME_AS_OLD(400, Translator.toLocale("new.password.same.as.old"), HttpStatus.BAD_REQUEST),
    INVALID_PHONE_NUMBER_FORMAT(
            400,
            Translator.toLocale("invalid.phone.number.format"),
            HttpStatus.BAD_REQUEST),
    INVALID_ROLE_NAME_AND_PERMISSION_BLANK(400, Translator.toLocale("invalid.role.name.and.permission.blank"), HttpStatus.BAD_REQUEST),
    INVALID_ROLE_NAME_AND_PERMISSION_FORMAT(
            400,
            Translator.toLocale("invalid.role.name.and.permission.format"),
            HttpStatus.BAD_REQUEST),
    INVALID_DESCRIPTION_BLANK(400, Translator.toLocale("invalid.description.blank"), HttpStatus.BAD_REQUEST),
    INVALID_PERMISSION_BLANK(400, Translator.toLocale("invalid.permission.blank"), HttpStatus.BAD_REQUEST),
    INVALID_OTP_BLANK(400, Translator.toLocale("invalid.otp.blank"), HttpStatus.BAD_REQUEST),
    INVALID_OTP_FORMAT(400, Translator.toLocale("invalid.otp.format"), HttpStatus.BAD_REQUEST),

    REFRESH_TOKEN_INVALID(400, Translator.toLocale("refresh.token.invalid"), HttpStatus.BAD_REQUEST),
    BUILDING_ID_REQUIRED(400,Translator.toLocale("building.id.required"), HttpStatus.BAD_REQUEST),
    REFRESH_TOKEN_EXPIRED(400, Translator.toLocale("refresh.token.expired"), HttpStatus.BAD_REQUEST),
    INVALID_OTP_CODE(400, Translator.toLocale("invalid.otp.code"), HttpStatus.BAD_REQUEST),
    INVALID_ISSUER(400, Translator.toLocale("invalid.issuer"), HttpStatus.BAD_REQUEST),
    INVALID_AUDIENCE(400, Translator.toLocale("invalid.audience"), HttpStatus.BAD_REQUEST),

    INVALID_FLOORS_NUMBER_FOR_RENT(
            400, Translator.toLocale("invalid.floors.number.for.rent"), HttpStatus.BAD_REQUEST),
    ACTUAL_FLOOR_NUMBER_IS_INVALID(400, Translator.toLocale("actual.floor.number.is.invalid"), HttpStatus.BAD_REQUEST),
    INVALID_RENTAL_FLOOR_NUMBER(400, Translator.toLocale("invalid.rental.floor.number"), HttpStatus.BAD_REQUEST),
    INVALID_BUILDING_CODE_BLANK(400, Translator.toLocale("invalid.building.code.blank"), HttpStatus.BAD_REQUEST),
    INVALID_BUILDING_NAME_BLANK(400, Translator.toLocale("invalid.building.name.blank"), HttpStatus.BAD_REQUEST),
    INVALID_ADDRESS_BLANK(400, Translator.toLocale("invalid.address.blank"), HttpStatus.BAD_REQUEST),
    INVALID_ACTUAL_NUMBER_OF_FLOORS_BLANK(400, Translator.toLocale("invalid.actual.number.of.floors.blank"), HttpStatus.BAD_REQUEST),
    INVALID_NUMBER_OF_FLOORS_FOR_RENT_BLANK(400, Translator.toLocale("invalid.number.of.floors.for.rent.blank"), HttpStatus.BAD_REQUEST),
    INVALID_BUILDING_TYPE_BLANK(400, Translator.toLocale("invalid.building.type.blank"), HttpStatus.BAD_REQUEST),
    INVALID_BUILDING_STATUS_BLANK(400, Translator.toLocale("invalid.building.status.blank"), HttpStatus.BAD_REQUEST),

    FLOOR_NAME_INVALID(400, Translator.toLocale("floor.name.invalid"), HttpStatus.BAD_REQUEST),
    MAX_ROOM_INVALID(400, Translator.toLocale("max.room.invalid"), HttpStatus.BAD_REQUEST),
    FLOOR_TYPE_INVALID(400, Translator.toLocale("floor.type.invalid"), HttpStatus.BAD_REQUEST),
    STATUS_TYPE_INVALID(400, Translator.toLocale("status.type.invalid"), HttpStatus.BAD_REQUEST),
    MAX_ROOM_AT_LEAST(400, Translator.toLocale("max.room.at.least"), HttpStatus.BAD_REQUEST),
    MAX_ROOM_SEARCH(400, Translator.toLocale("max.room.search"), HttpStatus.BAD_REQUEST),
    MAX_ROOM_AT_MOST(400, Translator.toLocale("max.room.at.most"), HttpStatus.BAD_REQUEST),
    FLOOR_ROOM_LIMIT_REACHED(400, Translator.toLocale("floor.room.limit.reached"), HttpStatus.BAD_REQUEST),

    INVALID_CUSTOMER_CODE_BLANK(400, Translator.toLocale("invalid.customer.code.blank"), HttpStatus.BAD_REQUEST),
    INVALID_ID_NUMBER_BLANK(400, Translator.toLocale("invalid.id.number.blank"), HttpStatus.BAD_REQUEST),
    INVALID_ID_NUMBER_FORMAT(400, Translator.toLocale("invalid.id.number.format"), HttpStatus.BAD_REQUEST),
    INVALID_TENANT_STATUS_BLANK(400, Translator.toLocale("invalid.tenant.status.blank"), HttpStatus.BAD_REQUEST),
    TENANT_CANNOT_BE_DELETED(400, Translator.toLocale("tenant.cannot.be.deleted"), HttpStatus.BAD_REQUEST),
    TENANT_CANNOT_BE_TOGGLED(400, Translator.toLocale("tenant.cannot.be.toggled"), HttpStatus.BAD_REQUEST),

    INVALID_VEHICLE_STATUS_BLANK(400, Translator.toLocale("invalid.vehicle.status.blank"), HttpStatus.BAD_REQUEST),
    INVALID_VEHICLE_TYPE_BLANK(400, Translator.toLocale("invalid.vehicle.type.blank"), HttpStatus.BAD_REQUEST),
    INVALID_LICENSE_PLATE_BLANK(400, Translator.toLocale("invalid.license.plate.blank"), HttpStatus.BAD_REQUEST),
    INVALID_REGISTRATION_DATE_BLANK(400, Translator.toLocale("invalid.registration.date.blank"), HttpStatus.BAD_REQUEST),
    INVALID_TENANT_ID_BLANK(400, Translator.toLocale("invalid.tenant.id.blank"), HttpStatus.BAD_REQUEST),
    INVALID_REGISTRATION_DATE(400, Translator.toLocale("invalid.registration.date"), HttpStatus.BAD_REQUEST),
    INVALID_LICENSE_PLATE(
            400, Translator.toLocale("invalid.license.plate"), HttpStatus.BAD_REQUEST),
    // Service Room Validation
    ROOM_ID_REQUIRED(400, Translator.toLocale("room.id.required"), HttpStatus.BAD_REQUEST),
    SERVICE_ID_REQUIRED(400, Translator.toLocale("service.id.required"), HttpStatus.BAD_REQUEST),
    START_DATE_REQUIRED(400, Translator.toLocale("start.date.required"), HttpStatus.BAD_REQUEST),
    START_DATE_MUST_BE_TODAY_OR_FUTURE(400, Translator.toLocale("start.date.must.be.today.or.future"), HttpStatus.BAD_REQUEST),
    TOTAL_PRICE_REQUIRED(400, Translator.toLocale("total.price.required"), HttpStatus.BAD_REQUEST),
    TOTAL_PRICE_MUST_BE_NON_NEGATIVE(400, Translator.toLocale("total.price.must.be.non.negative"), HttpStatus.BAD_REQUEST),
    STATUS_REQUIRED(400, Translator.toLocale("status.required"), HttpStatus.BAD_REQUEST),

    INVALID_DEFAULT_SERVICE_APPLIES_TO_NULL(400, Translator.toLocale("invalid.default.service.applies.to.null"), HttpStatus.BAD_REQUEST),
    INVALID_PRICES_APPLY_NULL(400, Translator.toLocale("invalid.prices.apply.null"), HttpStatus.BAD_REQUEST),
    INVALID_START_APPLYING_NULL(400, Translator.toLocale("invalid.start.applying.null"), HttpStatus.BAD_REQUEST),
    INVALID_DEFAULT_SERVICE_STATUS_NULL(400, Translator.toLocale("invalid.default.service.status.null"), HttpStatus.BAD_REQUEST),
    INVALID_BUILDING_ID_NULL(404, Translator.toLocale("invalid.building.id.null"), HttpStatus.NOT_FOUND),
    INVALID_SERVICE_ID_NULL(404, Translator.toLocale("invalid.service.id.null"), HttpStatus.NOT_FOUND),
    PRICES_APPLY_INVALID(400, Translator.toLocale("prices.apply.invalid"), HttpStatus.BAD_REQUEST),
    DUPLICATE_SERVICE(400, Translator.toLocale("duplicate.service"), HttpStatus.BAD_REQUEST),

    INVALID_NUMBER_OF_PEOPLE(400, Translator.toLocale("invalid.number.of.people"), HttpStatus.BAD_REQUEST),
    INVALID_START_DATE_BLANK(400, Translator.toLocale("invalid.start.date.blank"), HttpStatus.BAD_REQUEST),
    INVALID_END_DATE_BLANK(400, Translator.toLocale("invalid.end.date.blank"), HttpStatus.BAD_REQUEST),
    INVALID_DEPOSIT_BLANK(400, Translator.toLocale("invalid.deposit.blank"), HttpStatus.BAD_REQUEST),
    INVALID_DEPOSIT(400, Translator.toLocale("invalid.deposit"), HttpStatus.BAD_REQUEST),
    INVALID_TENANTS_BLANK(400, Translator.toLocale("invalid.tenants.blank"), HttpStatus.BAD_REQUEST),
    INVALID_TENANTS(400, Translator.toLocale("invalid.tenants"), HttpStatus.BAD_REQUEST),
    INVALID_CONTRACT_STATUS_BLANK(400, Translator.toLocale("invalid.contract.status.blank"), HttpStatus.BAD_REQUEST),
    NUMBER_OF_PEOPLE_EXCEEDS_LIMIT(400, Translator.toLocale("number.or.people.exceeds.limit"), HttpStatus.NOT_FOUND),
    END_DATE_BEFORE_START_DATE(400, Translator.toLocale("end.date.before.start.date"), HttpStatus.NOT_FOUND),
    TENANTS_EXCEEDS_NUMBER_OF_PEOPLE(
            400, Translator.toLocale("tenants.exceeds.number.of.people"), HttpStatus.NOT_FOUND),
    CANNOT_DELETE_CONTRACT(400, Translator.toLocale("cannot.delete.contract"), HttpStatus.NOT_FOUND),
    CANNOT_REACTIVATE_EXPIRED_CONTRACT(400, Translator.toLocale("cannot.reactivate.expired.contract"), HttpStatus.BAD_REQUEST),
    CANNOT_ACTIVATION_CONTRACT(400, Translator.toLocale("cannot.activation.contract"), HttpStatus.BAD_REQUEST),
    OWNER_ID_REQUIRED(400, Translator.toLocale("owner.id.required"), HttpStatus.BAD_REQUEST),
    IS_REPRESENTATIVE_REQUIRED(400, Translator.toLocale("is.representative.required"), HttpStatus.BAD_REQUEST),
    TENANT_ALREADY_IN_CONTRACT(
            400, Translator.toLocale("tenant.already.in.contract"), HttpStatus.BAD_REQUEST),
    TENANT_HAS_NO_CONTRACT(400, Translator.toLocale("tenant.has.no.contract"), HttpStatus.BAD_REQUEST),
    CANNOT_ADD_MORE_FLOORS(
            400, Translator.toLocale("cannot.add.more.floors"), HttpStatus.BAD_REQUEST),
    CANNOT_TOGGLE_SERVICE_STATUS(400, Translator.toLocale("cannot.toggle.service.status"), HttpStatus.BAD_REQUEST),
    CANNOT_TOGGLE_ASSET_STATUS(400, Translator.toLocale("cannot.toggle.asset.status"), HttpStatus.BAD_REQUEST),

    INVALID_TITLE_BLANK(400, Translator.toLocale("invalid.title.blank"), HttpStatus.BAD_REQUEST),
    INVALID_JOB_PRIORITY_LEVEL_NULL(400, Translator.toLocale("invalid.job.priority.level.null"), HttpStatus.BAD_REQUEST),
    INVALID_JOB_STATUS_NULL(400, Translator.toLocale("invalid.job.status.null"), HttpStatus.BAD_REQUEST),
    INVALID_COMPLETION_DEADLINE_NULL(400, Translator.toLocale("invalid.completion.deadline.null"), HttpStatus.BAD_REQUEST),
    INVALID_JOB_OBJECT_TYPE_NULL(400, Translator.toLocale("invalid.job.object.type.null"), HttpStatus.BAD_REQUEST),
    INVALID_COMPLETION_DEADLINE_PAST(400, Translator.toLocale("invalid.completion.deadline.past"), HttpStatus.BAD_REQUEST),
    INVALID_SERVICE_APPLIES(400, Translator.toLocale("invalid.service.applies"), HttpStatus.BAD_REQUEST),

    INVOICE_CREATION_FAILED(400, Translator.toLocale("invoice.creation.failed"), HttpStatus.BAD_REQUEST),
    INVOICE_ALREADY_EXISTS(400, Translator.toLocale("invoice.already.exists"), HttpStatus.BAD_REQUEST),
    CONTRACT_NOT_ACTIVE(400, Translator.toLocale("contract.not.active"), HttpStatus.BAD_REQUEST),
    INVALID_SERVICE_TYPE(400, Translator.toLocale("invalid.service.type"), HttpStatus.BAD_REQUEST),
    METER_TYPE_NOT_FOUND(400, Translator.toLocale("meter.type.not.found"), HttpStatus.BAD_REQUEST),
    DUPLICATE_INVOICE_DETAIL(400, Translator.toLocale("duplicate.invoice.detail"), HttpStatus.BAD_REQUEST),
    INVALID_METER_READING(
            400, Translator.toLocale("invalid.meter.reading"), HttpStatus.BAD_REQUEST),
    INVALID_COMPENSATION_DATA(400, Translator.toLocale("invalid.compensation.data"), HttpStatus.UNAUTHORIZED),
    INVOICE_ITEM_TYPE_NOT_NULL(400, Translator.toLocale("invoice.item.type.not.null"), HttpStatus.BAD_REQUEST),
    INVALID_NEW_INDEX_MIN(400, Translator.toLocale("invalid.new.index.min"), HttpStatus.BAD_REQUEST),
    INVALID_QUANTITY_MIN(400, Translator.toLocale("invalid.quantity.min"), HttpStatus.BAD_REQUEST),
    INVALID_UNIT_PRICE_MIN(400, Translator.toLocale("invalid.unit.price"), HttpStatus.BAD_REQUEST),
    CANNOT_DELETE_ROOM_CHARGE(400, Translator.toLocale("can.not.delete.room.charge"), HttpStatus.BAD_REQUEST),
    NOT_LAST_MONTH_OF_CONTRACT(400, Translator.toLocale("not.last.month.of.contract"), HttpStatus.BAD_REQUEST),
    MISSING_MAIN_INVOICE(400, Translator.toLocale("missing.main.invoice"), HttpStatus.BAD_REQUEST),
    DUPLICATE_END_INVOICE(400, Translator.toLocale("duplicate.end.invoice"), HttpStatus.BAD_REQUEST),
    INVOICE_ALREADY_CANCELLED(400, Translator.toLocale("invoice.already.cancelled"), HttpStatus.BAD_REQUEST),
    INVALID_INVOICE_STATUS(400, Translator.toLocale("invalid.invoice.status"), HttpStatus.BAD_REQUEST),
    INVOICE_NOT_EDITABLE(400, Translator.toLocale("invoice.not.editable"), HttpStatus.BAD_REQUEST),
    INVALID_PAYMENT_DUE_DATE(
            400, Translator.toLocale("invalid.payment.due.date"), HttpStatus.BAD_REQUEST),
    INVOICE_CAN_NOT_BE_DELETED(400, Translator.toLocale("invoice.can.not.be.deleted"), HttpStatus.BAD_REQUEST),
    INVALID_ASSETS_BLANK(400, Translator.toLocale("invalid.assets.blank"), HttpStatus.BAD_REQUEST),
    INVALID_ASSETS(400, Translator.toLocale("invalid.assets"), HttpStatus.BAD_REQUEST),

    INVALID_CATEGORY_WITH_CALCULATION(400, Translator.toLocale("invalid.category.with.calculation"), HttpStatus.BAD_REQUEST),
    UNIT_REQUIRED_FOR_CALCULATION(
            400, Translator.toLocale("unit.required.for.calculation"), HttpStatus.BAD_REQUEST),
    INVALID_UNIT_COMBINATION(
            400,
            Translator.toLocale("invalid.unit.combination"),
            HttpStatus.BAD_REQUEST),
    INVALID_SERVICE_NAME_BLANK(400, Translator.toLocale("invalid.service.name.blank"), HttpStatus.BAD_REQUEST),
    INVALID_SERVICE_CATEGORY_NULL(400, Translator.toLocale("invalid.service.category.null"), HttpStatus.BAD_REQUEST),
    INVALID_PRICE(400, Translator.toLocale("invalid.price"), HttpStatus.BAD_REQUEST),
    INVALID_PRICE_NULL(400, Translator.toLocale("invalid.price.null"), HttpStatus.BAD_REQUEST),
    INVALID_SERVICE_CALCULATION_NULL(400, Translator.toLocale("invalid.service.calculation.null"), HttpStatus.BAD_REQUEST),
    INVALID_SERVICE_STATUS_NULL(400, Translator.toLocale("invalid.service.status.null"), HttpStatus.BAD_REQUEST),
    METER_READING_ALREADY_BILLED(400, Translator.toLocale("meter.reading.already.billed"), HttpStatus.BAD_REQUEST),
    CONTRACT_EXPIRED(400, Translator.toLocale("contract.expired"), HttpStatus.BAD_REQUEST),
    SERVICE_ROOM_ALREADY_EXISTS(400, Translator.toLocale("service.room.already.exists"), HttpStatus.BAD_REQUEST),
    NEW_UNIT_PRICE_REQUIRED(400, Translator.toLocale("new.unit.price.required"), HttpStatus.BAD_REQUEST),
    UNIT_PRICE_REQUIRED(400, Translator.toLocale("unit.price.is.required"), HttpStatus.BAD_REQUEST),
    PRICE_MUST_BE_POSITIVE(400, Translator.toLocale("price.must.be.positive"), HttpStatus.BAD_REQUEST),
    INVALID_ASSET_TYPE_NOT_NULL(400, Translator.toLocale("invalid.asset.type.not.null"), HttpStatus.BAD_REQUEST),
    INVALID_SECURITY_ASSET_LOCATION(400, Translator.toLocale("invalid.security.asset.location"), HttpStatus.BAD_REQUEST),
    ASSET_NAME_NOT_BLANK(400, Translator.toLocale("asset.name.must.not.be.blank"), HttpStatus.BAD_REQUEST),
    ASSET_ROOM_ALREADY_EXISTS(400, Translator.toLocale("asset.room.already.exists"), HttpStatus.BAD_REQUEST),
    ASSET_BELONG_TO_REQUIRED(400, Translator.toLocale("asset.belong.to.required"), HttpStatus.BAD_REQUEST),
    INVALID_ASSET_BELONG_TO(400, Translator.toLocale("invalid.asset.belong.to.value"), HttpStatus.BAD_REQUEST),
    PUBLIC_ASSET(400, Translator.toLocale("you.cannot.add.shared.property.to.a.room"), HttpStatus.BAD_REQUEST),
    SERVICE_IDS_REQUIRED(400, Translator.toLocale("service.ids.required"), HttpStatus.BAD_REQUEST),
    ASSET_ID_REQUIRED(400, Translator.toLocale("asset.id.required"), HttpStatus.BAD_REQUEST),
    ROOM_NOT_FOUND_IN_BUILDING(400, Translator.toLocale("room.not.found.in.this.building"), HttpStatus.BAD_REQUEST),
    ASSET_NOT_ACTIVE(400, Translator.toLocale("asset.is.not.active"), HttpStatus.BAD_REQUEST),
    SERVICE_NOT_ACTIVE(400, Translator.toLocale("service.not.active"), HttpStatus.BAD_REQUEST),
    NO_PENDING_INVOICES(400, Translator.toLocale("no.pending.invoices"), HttpStatus.BAD_REQUEST),
    ALL_INVOICES_ALREADY_HAVE_RECEIPTS(400, Translator.toLocale("all.invoices.already.have.receipt"), HttpStatus.BAD_REQUEST),
    INVALID_PAYMENT_METHOD(400, Translator.toLocale("invalid.payment.method"), HttpStatus.BAD_REQUEST),
    NOT_SUPPORTED_YET(400, Translator.toLocale("not.supported.yet"), HttpStatus.BAD_REQUEST),
    CANNOT_REFUSE_PAYMENTS(400, Translator.toLocale("cannot.refuse.payments"), HttpStatus.BAD_REQUEST),
    INVALID_PAYMENT_STATUS(400, Translator.toLocale("invalid.payment.status"), HttpStatus.BAD_REQUEST),
    REASON_CAN_NOT_BE_NULL(400, Translator.toLocale("reason.can.not.be.null"), HttpStatus.BAD_REQUEST),
    INVALID_SERVICE_CATEGORY(400, Translator.toLocale("invalid.service.category"), HttpStatus.BAD_REQUEST),
    MISSING_NUMBER_OF_PEOPLE_IN_CONTRACT(400, Translator.toLocale("missing.number.of.people.in.contract"), HttpStatus.BAD_REQUEST),
    INVALID_VEHICLE_COUNT(400, Translator.toLocale("invalid.vehicle.count"), HttpStatus.BAD_REQUEST),
    INVALID_QUANTITY_NOT_NULL(400, Translator.toLocale("invalid.quantity.not.null"), HttpStatus.BAD_REQUEST),
    CONTRACT_NOT_ELIGIBLE_FOR_INVOICE(400, Translator.toLocale("contract.not.eligible.for.invoice"), HttpStatus.BAD_REQUEST),
    INVALID_SERVICE_CALCULATION(400, Translator.toLocale("invalid.service.calculation"), HttpStatus.BAD_REQUEST),
    ERROR_IN_CALCULATION_OF_SERVICE(400, Translator.toLocale("error.in.calculation.of.service"), HttpStatus.BAD_REQUEST),
    PAYMENT_DUE_DATE_IN_PAST(400, Translator.toLocale("payment.due.date.in.past"), HttpStatus.BAD_REQUEST),
    PAYMENT_DUE_DATE_TOO_FAR(400, Translator.toLocale("payment.due.date.too.far"), HttpStatus.BAD_REQUEST),
    NO_ACTIVE_CONTRACT_FOUND(400, Translator.toLocale("no.active.contract.found"), HttpStatus.BAD_REQUEST),
    QUANTITY_MUST_BE_POSITIVE(400, Translator.toLocale("quantity.must.be.greater.than.0"), HttpStatus.BAD_REQUEST),
    ASSET_QUANTITY_NOT_ENOUGH(400, Translator.toLocale("asset.quantity.is.not.enough"), HttpStatus.BAD_REQUEST),
    ROOM_ALREADY_HAS_ACTIVE_CONTRACT(400, "This room already has an active contract.", HttpStatus.BAD_REQUEST),
    ROOM_HAS_NO_ASSET(400, Translator.toLocale("room.has.no.asset"), HttpStatus.BAD_REQUEST),
    CONTRACT_MUST_HAVE_TENANT(400, Translator.toLocale("contract.must.have.tenant"), HttpStatus.BAD_REQUEST),
    MUST_HAVE_ONE_REPRESENTATIVE(400, Translator.toLocale("must.have.one.representative"), HttpStatus.BAD_REQUEST),
    VEHICLE_ALREADY_IN_ACTIVE_CONTRACT(400, Translator.toLocale("vehicle.already.in.active.contract"), HttpStatus.BAD_REQUEST),
    ROOM_ALREADY_IN_CONTRACT(400, Translator.toLocale("room.already.in.contract"), HttpStatus.BAD_REQUEST),
    NUMBER_OF_PEOPLE_MISMATCH(400, Translator.toLocale("number.of.people.mismatch"), HttpStatus.BAD_REQUEST),
    DUPLICATED_TENANTS_IN_REQUEST(400, Translator.toLocale("duplicated.tenants.in.request"), HttpStatus.BAD_REQUEST),
    INVALID_REPRESENTATIVE_SELECTION(400, Translator.toLocale("invalid.representative.selection"), HttpStatus.BAD_REQUEST),
    TENANT_NOT_IN_CONTRACT(400, Translator.toLocale("tenant.not.in.contract"), HttpStatus.BAD_REQUEST),
    CANNOT_DELETE_REPRESENTATIVE_TENANT(400, Translator.toLocale("cannot.delete.representative.tenant"), HttpStatus.BAD_REQUEST),
    REPRESENTATIVE_NOT_FOUND(400, Translator.toLocale("representative.not.found"), HttpStatus.BAD_REQUEST),
    REPRESENTATIVE_DUPLICATE(400, Translator.toLocale("representative.duplicate"), HttpStatus.BAD_REQUEST),
    VEHICLE_NOT_IN_CONTRACT(400, Translator.toLocale("vehicle.not.in.contract"), HttpStatus.BAD_REQUEST),
    CONTRACT_NOT_ALLOW_DELETE_DEPOSIT(400, Translator.toLocale("contract.not.allow.delete.deposit"), HttpStatus.BAD_REQUEST),
    DEPOSIT_ALREADY_EXISTS(400, Translator.toLocale("deposit.already.exists"), HttpStatus.BAD_REQUEST),
    CONTRACT_NOT_ALLOW_CONFIRM_DEPOSIT(400, Translator.toLocale("contract.not.allow.confirm.deposit"), HttpStatus.BAD_REQUEST),
    ROOM_NOT_AVAILABLE(400, Translator.toLocale("room.not.available"), HttpStatus.BAD_REQUEST),
    CANNOT_UPDATE_ROOM(400, Translator.toLocale("cannot.update.room"), HttpStatus.BAD_REQUEST),
    INVALID_CONTENT_IN_CONTRACT(400, Translator.toLocale("invalid.content.in.contract"), HttpStatus.BAD_REQUEST),
    INVALID_CONTRACT_STATUS_FOR_INVOICE(400, Translator.toLocale("invalid.contract.status.for.invoice"), HttpStatus.BAD_REQUEST),
    INVALID_END_DATE(400, Translator.toLocale("invalid.end.date"), HttpStatus.BAD_REQUEST),
    END_DATE_BEFORE_CURRENT(400,Translator.toLocale("end.date.before.current"),HttpStatus.BAD_REQUEST),
    CONTRACT_NOT_ELIGIBLE_FOR_EXTENSION(400,"", HttpStatus.BAD_REQUEST),
    TENANT_NOT_ELIGIBLE_FOR_CONTRACT(400,Translator.toLocale("tenant.not.eligible.for.contract"), HttpStatus.BAD_REQUEST),
    CANNOT_UPDATE_MAXIMUM_ROOM(400,Translator.toLocale("cannot.update.maximum.room"), HttpStatus.BAD_REQUEST),
    INVALID_CONTRACT_DURATION(400,Translator.toLocale("invalid.contract.duration"), HttpStatus.BAD_REQUEST),
    INVALID_MONTH(400,Translator.toLocale("invalid.month"), HttpStatus.BAD_REQUEST),
    ROOM_NOT_AVAILABLE_FOR_RENT(400,Translator.toLocale("room.not.available.for.rent"), HttpStatus.BAD_REQUEST),
    CONTRACT_NOT_ELIGIBLE_FOR_UPDATE(400,Translator.toLocale("contract.not.eligible.for.update"), HttpStatus.BAD_REQUEST),

    // Code: 404
    USER_NOT_FOUND(404, Translator.toLocale("user.not.found"), HttpStatus.NOT_FOUND),
    BUILDING_ID_NOT_FOUND(404, Translator.toLocale("building.id.not.found"), HttpStatus.NOT_FOUND),
    CHAT_NOT_FOUND(404, Translator.toLocale("chat.not.found"), HttpStatus.NOT_FOUND),
    MESSAGE_NOT_FOUND(404, Translator.toLocale("message.not.found"), HttpStatus.NOT_FOUND),
    API_ENDPOINT_NOT_FOUND(404, Translator.toLocale("api.endpoint.not.found"), HttpStatus.NOT_FOUND),
    PERMISSION_NOT_FOUND(404, Translator.toLocale("permission.not.found"), HttpStatus.NOT_FOUND),
    ROLE_NOT_FOUND(404, Translator.toLocale("role.not.found"), HttpStatus.NOT_FOUND),
    EMAIL_NOT_FOUND(404, Translator.toLocale("email.not.found"), HttpStatus.NOT_FOUND),
    BUILDING_NOT_FOUND(404, Translator.toLocale("building.not.found"), HttpStatus.NOT_FOUND),
    FLOOR_NOT_FOUND(404, Translator.toLocale("floor.not.found"), HttpStatus.NOT_FOUND),
    ROOM_NOT_FOUND(404, Translator.toLocale("room.not.found"), HttpStatus.NOT_FOUND),
    TENANT_NOT_FOUND(404, Translator.toLocale("tenant.not.found"), HttpStatus.NOT_FOUND),
    METER_READING_NOT_FOUND(404, Translator.toLocale("meter.reading.not.found"), HttpStatus.NOT_FOUND),
    ASSET_TYPE_NAME_INVALID(404, Translator.toLocale("asset.type.name.invalid"), HttpStatus.NOT_FOUND),
    ASSET_GROUP_INVALID(404, Translator.toLocale("asset.group.invalid"), HttpStatus.NOT_FOUND),
    DESCRIPTION_INVALID(404, Translator.toLocale("description.invalid"), HttpStatus.NOT_FOUND),
    ASSET_TYPE_NOT_FOUND(404, Translator.toLocale("asset.type.not.found"), HttpStatus.NOT_FOUND),
    ASSET_NOT_FOUND(404, Translator.toLocale("asset.not.found"), HttpStatus.NOT_FOUND),
    VEHICLE_NOT_FOUND(404, Translator.toLocale("vehicle.not.found"), HttpStatus.NOT_FOUND),
    METER_NOT_FOUND(404, Translator.toLocale("meter.not.found"), HttpStatus.NOT_FOUND),
    SERVICE_NOT_FOUND(404, Translator.toLocale("service.not.found"), HttpStatus.NOT_FOUND),
    CONTRACT_NOT_FOUND(404, Translator.toLocale("contract.not.found"), HttpStatus.NOT_FOUND),
    DEFAULT_SERVICE_NOT_FOUND(404, Translator.toLocale("default.service.not.found"), HttpStatus.NOT_FOUND),
    JOB_NOT_FOUND(404, Translator.toLocale("job.not.found"), HttpStatus.NOT_FOUND),
    METER_NAME_REQUIRED(404, Translator.toLocale("meter.name.required"), HttpStatus.NOT_FOUND),
    INITIAL_INDEX_REQUIRED(404, Translator.toLocale("initial.index.required"), HttpStatus.NOT_FOUND),
    METER_CODE_NOT_FOUND(404, Translator.toLocale("meter.code.not.found"), HttpStatus.NOT_FOUND),
    MANU_FACTURE_DATE_NOT_FOUND(404, Translator.toLocale("manu.facture.date.not.found"), HttpStatus.NOT_FOUND),
    METER_CODE_EXISTED(404, Translator.toLocale("meter.code.existed"), HttpStatus.NOT_FOUND),
    OLD_INDEX_NOT_FOUND(404, Translator.toLocale("old.index.not.found"), HttpStatus.NOT_FOUND),
    NEW_INDEX_NOT_FOUND(404, Translator.toLocale("new.index.not.found"), HttpStatus.NOT_FOUND),
    MONTH_NOT_FOUND(404, Translator.toLocale("month.not.found"), HttpStatus.NOT_FOUND),
    MONTH_GREATER(404, Translator.toLocale("month.greater"), HttpStatus.NOT_FOUND),
    MONTH_LESS(404, Translator.toLocale("month.less"), HttpStatus.NOT_FOUND),
    YEAR_NOT_FOUND(404, Translator.toLocale("year.not.found"), HttpStatus.NOT_FOUND),
    YEAR_GREATER(404, Translator.toLocale("year.greater"), HttpStatus.NOT_FOUND),
    READING_DATE_NOT_FOUND(404, Translator.toLocale("reading.date.not.found"), HttpStatus.NOT_FOUND),
    INVOICE_NOT_FOUND(404, Translator.toLocale("invoice.not.found"), HttpStatus.NOT_FOUND),
    INVOICE_ID_REQUIRED(404, Translator.toLocale("invoice.id.required"), HttpStatus.BAD_REQUEST),
    PAYMENT_METHOD_REQUIRED(404, Translator.toLocale("payment.method.required"), HttpStatus.BAD_REQUEST),
    PAYMENT_STATUS_REQUIRED(404,Translator.toLocale("payment.status.required"),HttpStatus.BAD_REQUEST),
    CONTRACT_TENANT_NOT_FOUND(404, Translator.toLocale("contract.tenant.not.found"), HttpStatus.NOT_FOUND),
    CONTRACT_VEHICLE_NOT_FOUND(404, Translator.toLocale("contract.vehicle.not.found"), HttpStatus.NOT_FOUND),
    DEPOSIT_NOT_FOUND(404, Translator.toLocale("deposit.not.found"), HttpStatus.NOT_FOUND),

    // feedback
    FEED_BACK_NOT_FOUND(404, Translator.toLocale("feedback.not.found"), HttpStatus.NOT_FOUND),
    CONTENT_NOT_FOUND(404, Translator.toLocale("content.not.found"), HttpStatus.BAD_REQUEST),
    RATING_NOT_FOUND(404, Translator.toLocale("rating.not.found"), HttpStatus.BAD_REQUEST),
    RATING_TOO_LOW(404, Translator.toLocale("rating.too.low"), HttpStatus.BAD_REQUEST),
    RATING_TOO_HIGH(404, Translator.toLocale("rating.too.high"), HttpStatus.BAD_REQUEST),
    FEED_BACK_STATUS_NOT_FOUND(404, Translator.toLocale("feedback.status.not.found"), HttpStatus.BAD_REQUEST),
    FEED_BACK_TYPE_NOT_FOUND(404, Translator.toLocale("feedback.type.not.found"), HttpStatus.BAD_REQUEST),
    FEED_BACK_DUPLICATED(404, Translator.toLocale("feed.back.duplicated"), HttpStatus.BAD_REQUEST),
    NOTE_NOT_FOUND(404, Translator.toLocale("note.not.found"), HttpStatus.NOT_FOUND),
    ASSET_STATUS_NOT_FOUND(404, Translator.toLocale("asset.status.not.found"), HttpStatus.NOT_FOUND),
    PAYMENT_RECEIPT_NOT_FOUND(404, Translator.toLocale("payment.receipt.not.found"), HttpStatus.NOT_FOUND),
    ASSET_ROOM_NOT_FOUND(404, Translator.toLocale("asset.room.not.found"), HttpStatus.NOT_FOUND),

    // notification
    NOTIFICATION_TITLE_REQUIRED(404, Translator.toLocale("notification.title.required"), HttpStatus.NOT_FOUND),
    NOTIFICATION_CONTENT_REQUIRED(404, Translator.toLocale("notification.content.required"), HttpStatus.NOT_FOUND),
    NOTIFICATION_TYPE_REQUIRED(404, Translator.toLocale("notification.type.required"), HttpStatus.NOT_FOUND),
    SEND_TO_ALL_REQUIRED(404, Translator.toLocale("send.to.all.required"), HttpStatus.NOT_FOUND),
    NOTIFICATION_USERS_REQUIRED(404, Translator.toLocale("notification.users.required"), HttpStatus.NOT_FOUND),
    NOTIFICATION_NOT_FOUND(404, Translator.toLocale("notification.not.found"), HttpStatus.NOT_FOUND),
    NOTIFICATION_NOT_ASSIGNED(404, Translator.toLocale("notification.not.assigned"), HttpStatus.NOT_FOUND),
    INVOICE_DETAIL_NOT_FOUND(404, Translator.toLocale("invoice.detail.not.found"), HttpStatus.NOT_FOUND),
    SERVICE_ROOM_CANNOT_DELETE(400, Translator.toLocale("service.room.cannot.delete"), HttpStatus.BAD_REQUEST),
    // Code: 409
    OTP_ALREADY_SENT(409, Translator.toLocale("otp.already.sent"), HttpStatus.BAD_REQUEST),
    USER_ALREADY_DELETED(409, Translator.toLocale("user.already.deleted"), HttpStatus.BAD_REQUEST),
    USER_ALREADY_LOCKED(409, Translator.toLocale("user.already.locked"), HttpStatus.BAD_REQUEST),
    EMAIL_EXISTED(409, Translator.toLocale("email.already.existed"), HttpStatus.CONFLICT),
    PHONE_NUMBER_EXISTED(409, Translator.toLocale("phone.number.existed"), HttpStatus.CONFLICT),
    FlOOR_EXISTED(409, Translator.toLocale("floor.existed"), HttpStatus.CONFLICT),
    FLOOR_ALREADY_EXISTS(409, Translator.toLocale("floor.already.exists"), HttpStatus.CONFLICT),
    PERMISSION_EXISTED(409, Translator.toLocale("permission.existed"), HttpStatus.BAD_REQUEST),
    ROLE_EXISTED(409, Translator.toLocale("role.existed"), HttpStatus.BAD_REQUEST),
    BUILDING_CODE_EXISTED(409, Translator.toLocale("building.code.existed"), HttpStatus.CONFLICT),
    BUILDING_NAME_EXISTED(409, Translator.toLocale("building.name.existed"), HttpStatus.CONFLICT),
    ROOM_CODE_EXISTED(409, Translator.toLocale("room.code.existed"), HttpStatus.BAD_REQUEST),
    ID_NUMBER_EXISTED(409, Translator.toLocale("id.number.existed"), HttpStatus.CONFLICT),
    ASSET_TYPE_EXISTED(409, Translator.toLocale("asset.type.existed"), HttpStatus.BAD_REQUEST),
    LICENSE_PLATE_EXISTED(409, Translator.toLocale("license.plate.existed"), HttpStatus.BAD_REQUEST),
    DUPLICATE_ASSET_NAME(409, Translator.toLocale("duplicate.asset.name"), HttpStatus.BAD_REQUEST),
    ROOM_EXISTED_SERVICE(409, Translator.toLocale("room.existed.service"), HttpStatus.BAD_REQUEST),
    SERVICE_ROOM_NOT_FOUND(409, Translator.toLocale("service.room.not.found"), HttpStatus.NOT_FOUND),
    ROOM_ALREADY_HAS_CONTRACT(409, Translator.toLocale("room.already.has.contract"), HttpStatus.BAD_REQUEST),
    NEW_INDEX_LESS_THAN_OLD(409, Translator.toLocale("new.index.less.than.old"), HttpStatus.BAD_REQUEST),
    METER_READING_EXISTED(409, Translator.toLocale("meter.reading.existed"), HttpStatus.CONFLICT),
    DUPLICATE_SERVICE_CATEGORY(409, Translator.toLocale("duplicate.service.category"), HttpStatus.BAD_REQUEST),
    METER_NAME_ALREADY_EXISTS_IN_ROOM(409,Translator.toLocale("meter.name.already.exists.in.this.room"),HttpStatus.BAD_REQUEST),
    METER_TYPE_ALREADY_EXISTS_IN_ROOM(409,Translator.toLocale("meter.type.already.exists.in.this.room"),HttpStatus.BAD_REQUEST),
    PAYMENT_RECEIPT_CANNOT_BE_UPDATED(409, Translator.toLocale("payment.receipt.cannot.be.updated"), HttpStatus.BAD_REQUEST),
    INVALID_PAYMENT_STATUS_CHANGE(409, Translator.toLocale("invalid.payment.status.change"), HttpStatus.BAD_REQUEST),
    PAYMENT_RECEIPT_ALREADY_EXISTS(409, Translator.toLocale("payment.receipt.already.exists"), HttpStatus.BAD_REQUEST),

    ;

    final int code;
    final String message;
    final HttpStatus status;

    ErrorCode(int code, String message, HttpStatus status) {
        this.code = code;
        this.message = message;
        this.status = status;
    }
}